# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_usergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
