# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0003_auto_20171019_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='用户组')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('user_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserCity')),
                ('user_group', models.ManyToManyField(to='app01.UserGroup')),
            ],
        ),
    ]
